name: flutter_keyboard
description: An improved clone of the numeric_keyboard package.
version: 2.0.0
homepage: https://github.com/diogoroos/flutter_keyboard

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0