name: flutter_keyboard
description: A customizable numeric keypad like those found on P.O.S equipment (P.D.V in Brazil)
version: 2.0.1
homepage: https://github.com/diogoroos/flutter_keyboard

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0